import localFont from 'next/font/local';
import './globals.css';
import { SidebarProvider } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/AppSidebar';
import EarthAnimation from '@/components/EarthAnimation';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Background Animation */}
        <div
          style={{
            position: 'absolute',
            top: 0,
            left: 0,
            width: '100%',
            height: '100%',
            zIndex: -1, // Send EarthAnimation to the background
          }}
        >
          <EarthAnimation />
        </div>

        {/* Sidebar and Main Content */}
        <div className='relative z-10 flex'>
          <SidebarProvider>
            <AppSidebar />
            <main className='flex-1 ml-64'>{children}</main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  );
}
